name: miji_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # 狀態管理
  provider: ^6.1.1
  
  # 地圖和位置服務
  google_maps_flutter: ^2.10.1
  # geolocator: ^11.0.0  # 暫時註釋掉以解決 iOS 構建問題
  
  # 本地存儲
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase 已完全移除，使用 Supabase 替代
  
  # UI 組件
  google_fonts: ^6.3.0
  confetti: ^0.8.0
  flutter_svg: ^2.0.9
  
  # 音頻播放
  audioplayers: ^5.2.1
  
  # HTTP 請求
  http: ^1.1.0
  
  # Supabase 服務
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/
